// Build db/import_inventory.sql from the inventory spreadsheet.
//
//   1. Open inventory.pdf's source workbook in Excel
//   2. File > Save As > CSV UTF-8  ->  db/inventory.csv
//   3. node db/build_inventory_sql.js
//
// Expected header: Item Name, Part Number, Brand, Vehicle Name, Price, Quantity
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'inventory.csv');
const OUT = path.join(__dirname, 'import_inventory.sql');

// --- minimal RFC4180 CSV parser (quoted fields contain commas and newlines) ---
function parseCsv(text) {
  const rows = [];
  let row = [], field = '', quoted = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; } else quoted = false;
      } else field += c;
    } else if (c === '"') quoted = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\r') { /* ignore */ }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else field += c;
  }
  if (field || row.length) { row.push(field); rows.push(row); }
  return rows;
}

const q = (s) => "'" + String(s).replace(/\\/g, '\\\\').replace(/'/g, "''") + "'";

// Cells wrap mid-word in the sheet; collapse whitespace and trim.
const clean = (s) => String(s == null ? '' : s).replace(/\s+/g, ' ').trim();

const num = (s) => {
  const n = parseFloat(String(s).replace(/[^0-9.\-]/g, ''));
  return Number.isFinite(n) ? n : 0;
};

const raw = fs.readFileSync(SRC, 'utf8').replace(/^\uFEFF/, '');
const rows = parseCsv(raw);
const header = rows.shift().map((h) => clean(h).toLowerCase());
const col = (want) => {
  const i = header.findIndex((h) => h === want);
  if (i === -1) throw new Error(`column "${want}" not found in: ${header.join(' | ')}`);
  return i;
};
const iName = col('item name'), iPart = col('part number'), iBrand = col('brand');
const iVeh = col('vehicle name'), iPrice = col('price'), iQty = col('quantity');

const values = [];
const skipped = [];
const seen = new Map();
const dupes = [];

rows.forEach((r, n) => {
  const line = n + 2; // 1-based, past the header
  const name = clean(r[iName]);
  const part = clean(r[iPart]);
  const make = clean(r[iBrand]);
  const model = clean(r[iVeh]);
  const price = num(r[iPrice]);
  let qty = Math.trunc(num(r[iQty]));

  // A row with no part number can't be looked up or reordered — the catalog
  // search is part-number first. Report it rather than inserting a blank key.
  if (!part) { skipped.push({ line, why: 'no part number', name }); return; }
  if (!name) { skipped.push({ line, why: 'no item name', part }); return; }

  // Negative stock is a counting error; clamp so the cart maths stays sane.
  if (qty < 0) { skipped.push({ line, why: `negative qty ${qty}, clamped to 0`, part }); qty = 0; }

  const key = [part, make, model].join('\u0000').toUpperCase();
  if (seen.has(key)) { dupes.push({ line, part, make, model, first: seen.get(key) }); return; }
  seen.set(key, line);

  values.push(`(${q(part)},${q(name)},${q(make)},${q(model)},${price},${qty})`);
});

const sql = `-- ============================================================
-- import_inventory.sql — Techno Automotives stock load into \`parts\`
-- GENERATED by db/build_inventory_sql.js on ${new Date().toISOString().slice(0, 10)}
-- Source: db/inventory.csv  (${rows.length} sheet rows -> ${values.length} parts)
--
-- Run db/migrations/001_parts_multi_brand.sql FIRST.
--
-- Mapping: Item Name->name, Part Number->part_number, Brand->make,
--          Vehicle Name->model, Price->price, Quantity->stock_qty
--
-- Re-runnable: an existing (part_number, make, model) line has its price and
-- name refreshed and its quantity SET to the sheet value (stock take, not a
-- delivery note). Uses VALUES() so it runs on MySQL 5.7+ and MariaDB.
-- ============================================================
USE sasaparts_b2b;

START TRANSACTION;

INSERT INTO parts (part_number, name, make, model, price, stock_qty) VALUES
${values.join(',\n')}
ON DUPLICATE KEY UPDATE
  name      = VALUES(name),
  price     = VALUES(price),
  stock_qty = VALUES(stock_qty);

COMMIT;
`;

fs.writeFileSync(OUT, sql);

console.log(`wrote ${OUT}`);
console.log(`  ${values.length} parts from ${rows.length} rows`);
if (dupes.length) {
  console.log(`\n  ${dupes.length} duplicate (part, brand, vehicle) rows skipped — same line counted twice:`);
  dupes.slice(0, 20).forEach((d) => console.log(`    line ${d.line}: ${d.part} / ${d.make} / ${d.model} (first seen line ${d.first})`));
  if (dupes.length > 20) console.log(`    ...and ${dupes.length - 20} more`);
}
if (skipped.length) {
  console.log(`\n  ${skipped.length} rows needing attention:`);
  skipped.slice(0, 30).forEach((s) => console.log(`    line ${s.line}: ${s.why} ${s.name || s.part || ''}`));
  if (skipped.length > 30) console.log(`    ...and ${skipped.length - 30} more`);
}
