// Run with: node db/build_supabase_inventory.js
// Reads db/inventory.csv and writes db/supabase_inventory.sql (PostgreSQL syntax).
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'inventory.csv');
const OUT = path.join(__dirname, 'supabase_inventory.sql');

// --- RFC4180 CSV parser: handles quoted fields with commas and newlines ---
function parseCsv(text) {
  const rows = [];
  let row = [], field = '', inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; } else { inQuotes = false; }
      } else field += c;
    } else if (c === '"') inQuotes = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else if (c !== '\r') field += c;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows;
}

const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";
const clean = (s) => String(s == null ? '' : s).replace(/\s+/g, ' ').trim();
const num = (s) => { const n = parseFloat(String(s).replace(/[^0-9.\-]/g, '')); return Number.isFinite(n) ? n : 0; };

const text = fs.readFileSync(SRC, 'utf8').replace(/^﻿/, '');
const rows = parseCsv(text).filter((r) => r.some((c) => clean(c)));
const header = rows.shift().map((h) => clean(h).toLowerCase());
const col = (name) => header.indexOf(name);
const iName = col('item name'), iPart = col('part number'), iBrand = col('brand'),
      iVeh = col('vehicle name'), iPrice = col('price'), iQty = col('quantity');

const seen = new Set();
const out = [];
let skippedNoPart = 0, skippedDup = 0, negQty = 0;

for (const r of rows) {
  const part = clean(r[iPart]), name = clean(r[iName]);
  if (!part || !name) { skippedNoPart++; continue; }
  // Trailing slashes are an artefact of the source sheet ("OZONE/", "KYB/").
  const make = clean(r[iBrand]).replace(/\/+$/, '');
  const model = clean(r[iVeh]).replace(/\/+$/, '');
  const key = (part + '|' + make + '|' + model).toUpperCase();
  if (seen.has(key)) { skippedDup++; continue; }
  seen.add(key);
  let qty = Math.round(num(r[iQty]));
  if (qty < 0) { qty = 0; negQty++; }
  out.push(`(${q(part)},${q(name)},${q(make)},${q(model)},${num(r[iPrice])},${qty})`);
}

const sql = `-- Techno Automotives parts catalogue for PostgreSQL / Supabase.
-- GENERATED by db/build_supabase_inventory.js on ${new Date().toISOString().slice(0, 10)}
-- Source: db/inventory.csv (${rows.length} sheet rows -> ${out.length} parts)
-- Run db/supabase_schema.sql FIRST — this needs the parts table and its unique key.
-- Safe to re-run: existing lines are updated, not duplicated.

INSERT INTO parts (part_number, name, make, model, price, stock_qty) VALUES
${out.join(',\n')}
ON CONFLICT (part_number, make, model) DO UPDATE SET
  name      = EXCLUDED.name,
  price     = EXCLUDED.price,
  stock_qty = EXCLUDED.stock_qty;
`;

fs.writeFileSync(OUT, sql);
console.log(`wrote ${OUT}`);
console.log(`  parts:             ${out.length}`);
console.log(`  skipped, no part#: ${skippedNoPart}`);
console.log(`  skipped, dupes:    ${skippedDup}`);
console.log(`  negative qty -> 0: ${negQty}`);
console.log(`  bytes:             ${fs.statSync(OUT).size}`);
